# Reference: 
# https://github.com/actions/checkout
# https://github.com/actions/setup-node
# https://docs.npmjs.com/cli/v8/commands/npm-ci

name: CI

on:
  pull_request:
    branches:
      - develop

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:  

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      #- run: npm ci
      - run: npm install

      - run: npm run lint:check

      - run: npm run style:check

      - run: npm run test:unit -- --coverage
        env:
          CI: true

      - run: npm run test:functional

