name: Shell Commands

on: [push, pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-20.04
    steps:
      - name: echo a string
        run: echo "It's running fine!!!!"
      - name: multiline script
        run: |
          node --version
          npm --version