# Reference: 
# https://github.com/actions/checkout
# https://github.com/actions/setup-node
# https://docs.npmjs.com/cli/v8/commands/npm-ci
# https://github.com/actions/cache
# -----------------------------------------------------------------------

name: CI

on:

  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop

jobs:

  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node: [ '12', '14', '16', '17' ]

    name: Node ${{ matrix.node }} sample

    steps:  

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-package-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-package-

      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      #- run: npm ci
      - run: npm install

      - run: npm run lint:check

      - run: npm run style:check

      - run: npm run test:unit -- --coverage
        env:
          CI: true

      - run: npm run test:functional

      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build

